version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: rust_mysql
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p${MYSQL_ROOT_PASSWORD}"]
      timeout: 20s
      retries: 10
      start_period: 30s

  app:
    build: .
    container_name: rust_api
    restart: always
    ports:
      - "${APP_PORT}:8080"
    env_file:
      - .env
    environment:
      # Menambahkan DATABASE_URL untuk aplikasi Rust
      DATABASE_URL: mysql://root:${MYSQL_ROOT_PASSWORD}@db:3306/${MYSQL_DATABASE}?allowPublicKeyRetrieval=true
    depends_on:
      db:
        condition: service_healthy

volumes:
  db_data: