[package]
name = "migration"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1", features = ["full"] }
sea-orm-migration = "0.15"

[lib]
name = "migration"
path = "src/lib.rs"

[[bin]]
name = "migration-bin"
path = "src/main.rs"
